# Generated by Django 3.2.7 on 2021-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('HR', 'Horror'), ('CM', 'Comedy')], max_length=2, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('likes', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('genres', models.ManyToManyField(related_name='movies', to='hollymovies_app.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=512)),
                ('movies', models.ManyToManyField(related_name='actors', to='hollymovies_app.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
