# Generated by Django 3.2.7 on 2021-10-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='oscars',
            field=models.IntegerField(default=0),
        ),
    ]
