# Generated by Django 3.2.7 on 2021-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0002_actor_oscars'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
